"""Wheelbipe V14 locomotion environments."""

from .base import (
    COMPACT_PRIVILEGED_OBS_HEIGHT_CLIP,
    COMPACT_PRIVILEGED_OBS_HEIGHT_SCALE,
    COMPACT_PRIVILEGED_ROOT_LINVEL_CLIP,
    GIMBAL_ACTUATOR_NAMES,
    GIMBAL_JOINT_NAMES,
    LEG_JOINT_NAMES,
    NATIVE_ACTUATOR_NAMES,
    NATIVE_ACTUATOR_NAMES_WITH_GIMBAL,
    NUM_LEG_ACTIONS,
    NUM_NATIVE_ACTUATORS,
    NUM_NATIVE_ACTUATORS_WITH_GIMBAL,
    NUM_POLICY_ACTIONS,
    NUM_WHEEL_ACTIONS,
    POLICY_JOINT_NAMES,
    POLICY_OBS_CLIP,
    POLICY_OBS_DIM,
    PRIVILEGED_OBS_DIM,
    SPRING_JOINT_NAMES,
    WHEEL_JOINT_NAMES,
    WHEELBIPE_DELAY_PROFILE_LOCAL,
    WHEELBIPE_DELAY_PROFILE_SOURCE,
    WHEELBIPE_DELAY_PROFILE_SOURCE_V14,
    WHEELBIPE_DELAY_PROFILES,
    WheelbipeControlConfig,
    WheelbipeGimbalConfig,
    WheelbipeNoiseConfig,
    build_wheelbipe_policy_observation,
    build_wheelbipe_timing_contract,
    canonical_wheelbipe_delay_profile,
    canonical_wheelbipe_delay_range_semantics,
    compute_wheelbipe_motor_ctrl,
    map_policy_action_to_native_targets,
    normalize_wheelbipe_delay_range,
    resolve_wheelbipe_torque_limits,
    sample_wheelbipe_delay_lags,
    wheelbipe_delay_profile_overrides,
)

# The upstream project exposes these exact IDs through ``gym.make``.  Keep the
# UniLab registry as the owner of construction, while registering a thin
# single-environment facade for source-compatible callers.  Registration is
# idempotent and does not import optional simulator modules until construction.
from .gym_adapter import register_wheelbipe_gym_envs
from .joystick import (
    WheelbipeCommands,
    WheelbipeDomainRandConfig,
    WheelbipeEnv,
    WheelbipeJointFrictionRandomizationConfig,
    WheelbipeRewardConfig,
    WheelbipeV14DomainRandomizationProvider,
    WheelbipeV14Env,
    WheelbipeV14FlatCfg,
    WheelbipeV14FlatEnv,
    WheelbipeV14FlatEnvCfg,
)
from .rough import (
    WheelbipeRoughTerrainCfg,
    WheelbipeV14RoughCfg,
    WheelbipeV14RoughEnv,
    WheelbipeV14RoughEnvCfg,
)
from .state_machine import (
    WheelbipeAirborneCommandResampleConfig,
    WheelbipeAirborneRewardConfig,
    WheelbipeMotionState,
    WheelbipeStateMachine,
    WheelbipeStateMachineConfig,
    WheelbipeTerrainCommandConfig,
    WheelbipeTerrainCommandProfileConfig,
)

# Import named upstream variants during registry bootstrap.  Registration is
# import-time by design in UniLab; leaving this module unimported would make
# the variant classes unreachable through ``registry.make``.
from .variants import (
    COMPACT_POLICY_OBS_DIM,
    UPSTREAM_WHEELBIPE_TASK_IDS,
    WheelbipeCustomEnv,
    WheelbipeCustomFlatCfg,
    WheelbipeDreamWaQCfg,
    WheelbipeDreamWaQPlayCfg,
    WheelbipeFlatPlayV0Cfg,
    WheelbipeFlatPlayV2Cfg,
    WheelbipeFlatV0Cfg,
    WheelbipeFlatV1Cfg,
    WheelbipeFlatV2Cfg,
    WheelbipeHIMCfg,
    WheelbipeHIMPlayCfg,
    WheelbipeNP3OCfg,
    WheelbipeNP3OPlayCfg,
    WheelbipeRoughPlayV0Cfg,
    WheelbipeRoughPlayV1Cfg,
    WheelbipeRoughV0Cfg,
    WheelbipeRoughV1Cfg,
    WheelbipeVariantCfg,
    WheelbipeVariantEnv,
)

register_wheelbipe_gym_envs()

__all__ = [
    "LEG_JOINT_NAMES",
    "GIMBAL_ACTUATOR_NAMES",
    "GIMBAL_JOINT_NAMES",
    "COMPACT_PRIVILEGED_OBS_HEIGHT_CLIP",
    "COMPACT_PRIVILEGED_OBS_HEIGHT_SCALE",
    "COMPACT_PRIVILEGED_ROOT_LINVEL_CLIP",
    "NATIVE_ACTUATOR_NAMES",
    "NATIVE_ACTUATOR_NAMES_WITH_GIMBAL",
    "NUM_LEG_ACTIONS",
    "NUM_NATIVE_ACTUATORS",
    "NUM_NATIVE_ACTUATORS_WITH_GIMBAL",
    "NUM_POLICY_ACTIONS",
    "NUM_WHEEL_ACTIONS",
    "POLICY_JOINT_NAMES",
    "POLICY_OBS_CLIP",
    "POLICY_OBS_DIM",
    "PRIVILEGED_OBS_DIM",
    "SPRING_JOINT_NAMES",
    "WHEEL_JOINT_NAMES",
    "WheelbipeCommands",
    "WheelbipeControlConfig",
    "WheelbipeGimbalConfig",
    "WheelbipeMotionState",
    "WheelbipeAirborneCommandResampleConfig",
    "WheelbipeAirborneRewardConfig",
    "WheelbipeStateMachine",
    "WheelbipeStateMachineConfig",
    "WheelbipeTerrainCommandConfig",
    "WheelbipeTerrainCommandProfileConfig",
    "WheelbipeDomainRandConfig",
    "WheelbipeJointFrictionRandomizationConfig",
    "WheelbipeNoiseConfig",
    "WheelbipeRewardConfig",
    "WheelbipeRoughTerrainCfg",
    "WheelbipeV14DomainRandomizationProvider",
    "WheelbipeV14Env",
    "WheelbipeV14FlatEnv",
    "WheelbipeV14FlatCfg",
    "WheelbipeV14FlatEnvCfg",
    "WheelbipeEnv",
    "WheelbipeV14RoughCfg",
    "WheelbipeV14RoughEnvCfg",
    "WheelbipeV14RoughEnv",
    "build_wheelbipe_policy_observation",
    "build_wheelbipe_timing_contract",
    "canonical_wheelbipe_delay_profile",
    "canonical_wheelbipe_delay_range_semantics",
    "compute_wheelbipe_motor_ctrl",
    "map_policy_action_to_native_targets",
    "normalize_wheelbipe_delay_range",
    "resolve_wheelbipe_torque_limits",
    "sample_wheelbipe_delay_lags",
    "wheelbipe_delay_profile_overrides",
    "WHEELBIPE_DELAY_PROFILE_LOCAL",
    "WHEELBIPE_DELAY_PROFILE_SOURCE",
    "WHEELBIPE_DELAY_PROFILE_SOURCE_V14",
    "WHEELBIPE_DELAY_PROFILES",
    "COMPACT_POLICY_OBS_DIM",
    "WheelbipeVariantCfg",
    "WheelbipeVariantEnv",
    "WheelbipeCustomEnv",
    "WheelbipeCustomFlatCfg",
    "WheelbipeFlatV0Cfg",
    "WheelbipeFlatV1Cfg",
    "WheelbipeFlatV2Cfg",
    "WheelbipeFlatPlayV0Cfg",
    "WheelbipeFlatPlayV2Cfg",
    "WheelbipeRoughV0Cfg",
    "WheelbipeRoughV1Cfg",
    "WheelbipeRoughPlayV0Cfg",
    "WheelbipeRoughPlayV1Cfg",
    "WheelbipeDreamWaQCfg",
    "WheelbipeDreamWaQPlayCfg",
    "WheelbipeHIMCfg",
    "WheelbipeHIMPlayCfg",
    "WheelbipeNP3OCfg",
    "WheelbipeNP3OPlayCfg",
    "UPSTREAM_WHEELBIPE_TASK_IDS",
    "register_wheelbipe_gym_envs",
]
