"""Shared training helpers for entrypoint scripts."""

from unilab.training.backend_adapter import BackendAdapter
from unilab.training.common import (
    assert_offpolicy_task_choice_matches_algo,
    create_env,
    ensure_registries,
    get_hydra_runtime_choice,
    setup_logger,
)
from unilab.training.experiment import ExperimentTracker
from unilab.training.monitoring import HardwareMonitor
from unilab.training.run import (
    format_hora_stage2_checkpoint_error,
    get_entrypoint_log_root,
    get_latest_checkpoint,
    get_latest_run,
    get_log_root,
    log_playback_plan,
    parse_checkpoint_path,
    resolve_appo_checkpoint_path,
    resolve_checkpoint_path,
    resolve_hora_stage2_checkpoint_path,
    resolve_latest_checkpoint_within_runs,
    resolve_offpolicy_checkpoint_path,
    resolve_task_checkpoint_path,
    should_run_playback,
)
from unilab.training.seed import (
    TrainingSeedInfo,
    apply_configured_training_seed,
    apply_training_seed,
    derive_worker_seed,
    resolve_training_seed,
)
from unilab.training.sim2sim import (
    CrossBackendIncompatibleError,
    hydrate_custom_checkpoint_config,
)
from unilab.training.wheelbipe_ros2 import (
    WHEELBIPE_ROS2_QOS,
    WheelbipeRos2Controller,
    WheelbipeRos2ControllerAdapter,
    WheelbipeRos2ControllerConfig,
    WheelbipeRos2ControllerState,
    WheelbipeRos2RobotState,
    decode_wheelbipe_real_command_packet,
    decode_wheelbipe_real_state_packet,
    encode_wheelbipe_real_command_packet,
    encode_wheelbipe_real_state_packet,
    wheelbipe_crc16,
    wheelbipe_ros2_contract_snapshot,
    wheelbipe_ros2_runtime_available,
)

__all__ = [
    "BackendAdapter",
    "ExperimentTracker",
    "HardwareMonitor",
    "assert_offpolicy_task_choice_matches_algo",
    "create_env",
    "ensure_registries",
    "get_entrypoint_log_root",
    "get_hydra_runtime_choice",
    "get_latest_checkpoint",
    "get_latest_run",
    "get_log_root",
    "log_playback_plan",
    "parse_checkpoint_path",
    "resolve_checkpoint_path",
    "resolve_task_checkpoint_path",
    "should_run_playback",
    "TrainingSeedInfo",
    "apply_configured_training_seed",
    "apply_training_seed",
    "derive_worker_seed",
    "format_hora_stage2_checkpoint_error",
    "resolve_appo_checkpoint_path",
    "resolve_hora_stage2_checkpoint_path",
    "resolve_latest_checkpoint_within_runs",
    "resolve_offpolicy_checkpoint_path",
    "resolve_training_seed",
    "CrossBackendIncompatibleError",
    "hydrate_custom_checkpoint_config",
    "setup_logger",
    "WHEELBIPE_ROS2_QOS",
    "WheelbipeRos2Controller",
    "WheelbipeRos2ControllerAdapter",
    "WheelbipeRos2ControllerConfig",
    "WheelbipeRos2ControllerState",
    "WheelbipeRos2RobotState",
    "decode_wheelbipe_real_state_packet",
    "decode_wheelbipe_real_command_packet",
    "encode_wheelbipe_real_command_packet",
    "encode_wheelbipe_real_state_packet",
    "wheelbipe_crc16",
    "wheelbipe_ros2_contract_snapshot",
    "wheelbipe_ros2_runtime_available",
]
